--4-1
DESC EMP;

--4-2, 3
DESC DEPT;
DESC SALGRADE;

-- 4-4
SELECT * FROM EMP WHERE ROWNUM = 1;

-- 4-5
SELECT empno, ename, deptno
  FROM emp;
  
-- 4-6 중복 데이타를 삭제하는 DISTINCT
SELECT DISTINCT DEPTNO
  FROM EMP;

-- 4-7 열이 여러개
SELECT DISTINCT DEPTNO, JOB
  FROM EMP;

-- 4-8 ALL 중복되는 열 제거 없이 그대로 출력
SELECT ALL DEPTNO, JOB
  FROM EMP;

-- 4-9 열에 연산식을 사용
SELECT ENAME, SAL, SAL*12+COMM ANNSAL, COMM FROM EMP;
SELECT ENAME, SAL, SAL*12+COMM "ANNSAL", COMM FROM EMP;
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM FROM EMP;
SELECT ENAME, SAL, SAL*12+COMM AS "ANNSAL", COMM FROM EMP;


-- 4-10 열에 연산식을 사용
SELECT ENAME, SAL 
     , SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+COMM ANNSAL
     , COMM
  FROM EMP;  
  
-- 4-11
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM FROM EMP;

-- 4-12  원하는 순서로 출력 데이터를 정렬하는 ORDER BY
SELECT * 
  FROM EMP 
 ORDER BY SAL;

-- 4-12 1분 실습: 사원번호 기준 오름차순 정렬
SELECT * 
  FROM EMP
 ORDER BY EMPNO; 
 
-- 4-13 급여기준 내림차순: 많이 받는 사람순
SELECT *
  FROM EMP
 ORDER BY SAL DESC;
 
-- 4-13 최근 입사한 순으로 조회
SELECT *
  FROM EMP
 ORDER BY HIREDATE DESC;
 
 -- 1-14 각각의 열에 내림차순과 오름차순  동시에 사용하기
 SELECT *
   FROM EMP
  ORDER BY DEPTNO ASC, SAL DESC; 
  
SELECT DISTINCT JOB
  FROM EMP;
  
SELECT EMPNO AS EMPLOYEE_NO
     , ENAME AS EMPLOYEE_NAME
     , JOB
     , MGR AS MANAGER
     , HIREDATE
     , SAL AS SALARY
     , COMM AS COMMISSION
     , DEPTNO AS DEPARTMENT_NO
  FROM EMP
 ORDER BY DEPTNO DESC, ENAME;
  
-- 1 테이블 전체 조회
SELECT *
  FROM DEPARTMENTS;
-- 2. 특정 컬럼만 조회
SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME 
  FROM DEPARTMENTS;
-- 3. 별칭 컬럼
SELECT DEPARTMENT_ID AS 부서ID
     , DEPARTMENT_NAME AS 부서이름
  FROM DEPARTMENTS;
-- 4. 중복제외 DISTINCT
SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS;
-- 5. 산술연산
SELECT FIRST_NAME, LAST_NAME
     , SALARY, SALARY + 500, SALARY * 1.1
     , SALARY - 500 , SALARY / 1.2
  FROM EMPLOYEES;

-- 연결연산자 :   ||
SELECT DEPARTMENT_ID || ' ' || DEPARTMENT_NAME AS 부서이름
     , DEPARTMENT_NAME || ' (' || DEPARTMENT_ID || ')' AS 부서명
  FROM DEPARTMENTS;

SELECT *
  FROM countries;
  
SELECT COUNTRY_ID, COUNTRY_NAME
  FROM COUNTRIES;
SELECT COUNTRY_ID 국가ID, COUNTRY_NAME 국가명
  FROM COUNTRIES;
SELECT DISTINCT REGION_ID
  FROM COUNTRIES;
SELECT COUNTRY_NAME || COUNTRY_ID
  FROM COUNTRIES;
  
SELECT STREET_ADDRESS, CITY
  FROM LOCATIONS  ;

SELECT job_id, job_title
  FROM JOBS;
  
SELECT job_title, min_salary*1.1 AS 최소연봉
     , max_salary*1.1 AS 최대연봉
  FROM JOBS;
  
SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름
  FROM EMPLOYEES;
  
SELECT DISTINCT JOB_ID
  FROM EMPLOYEES;
  
  
  