-- 8장 조인

-- 8-1
-- SQL-99 이전 방식
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL 
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.SAL > 2000
 ORDER BY D.DEPTNO;
  
-- SQL-99방식 
SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
  FROM EMP E NATURAL JOIN DEPT D
 WHERE E.SAL > 2000
 ORDER BY DEPTNO;
  
-- 8-2
-- SQL-99 이전 방식
SELECT D.DEPTNO
     , D.DNAME
     , TRUNC(AVG(E.SAL)) AS AVG_SAL
     , MAX(E.SAL) AS MAX_SAL
     , MIN(E.SAL) AS MIN_SAL
     , COUNT(*) AS CNT 
 FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO
     , D.DNAME;
     
     
-- SQL-99방식 
SELECT DEPTNO
     , D.DNAME
     , TRUNC(AVG(E.SAL)) AS AVG_SAL
     , MAX(E.SAL) AS MAX_SAL
     , MIN(E.SAL) AS MIN_SAL
     , COUNT(*) AS CNT 
 FROM EMP E JOIN DEPT D USING ( DEPTNO )
GROUP BY DEPTNO, D.DNAME;

SELECT E.DEPTNO
     , D.DNAME
     , TRUNC(AVG(E.SAL)) AS AVG_SAL
     , MAX(E.SAL) AS MAX_SAL
     , MIN(E.SAL) AS MIN_SAL
     , COUNT(*) AS CNT 
 FROM EMP E JOIN DEPT D ON ( E.DEPTNO = D.DEPTNO )
GROUP BY E.DEPTNO, D.DNAME;
     
SELECT DISTINCT DEPTNO FROM EMP;

-- 8-3
-- SQL-99 이전 방식
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL 
  FROM DEPT D, EMP E
 WHERE D.DEPTNO = E.DEPTNO(+)
 ORDER BY D.DEPTNO, D.DNAME;
  
-- SQL-99방식 
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM DEPT D LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
 ORDER BY D.DEPTNO, D.DNAME;

-- 8-4
--SQL-99 이전 방식
SELECT D.DEPTNO, D.DNAME
     , E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO
     , S.LOSAL, S.HISAL, S.GRADE
     , M.EMPNO AS MGR_EMPNO,  M.ENAME AS MGR_ENAME
 FROM  DEPT D
     , EMP E
     , SALGRADE S
     , EMP M
 WHERE D.DEPTNO = E.DEPTNO(+)
   AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
   AND E.MGR = M.EMPNO(+)
 ORDER BY D.DEPTNO, E.EMPNO;


--SQL-99방식
SELECT D.DEPTNO, D.DNAME
     , E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO
     , S.LOSAL, S.HISAL, S.GRADE
     , M.EMPNO AS MGR_EMPNO,  M.ENAME AS MGR_ENAME
 FROM  DEPT D LEFT OUTER JOIN EMP E  ON (D.DEPTNO = E.DEPTNO)
       LEFT OUTER JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
       LEFT OUTER JOIN EMP M ON (E.MGR = M.EMPNO)
 ORDER BY D.DEPTNO, E.EMPNO;
 

